# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Sam",
  "email": "sam@post.go",
  "status": "regular",
  "password": "qwerty123"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "sam@post.go",
  "password": "qwerty123"
}

###

## Получить список избранного пользователя

GET http://localhost:4000/users/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNhbUBwb3N0LmdvIiwibmFtZSI6IlNhbSIsImlkIjoiNjU0OGU1ODk1NmFlMDE1MDQ3NWJmOGE4IiwiaXNQcm8iOmZhbHNlLCJpYXQiOjE2OTk5ODQzNzAsImV4cCI6MTcwMDE1NzE3MH0.0gDlFXUk_4Nkdl15NmQD3q-HRsrcDszumE5ROkHmzow

###

## Добавить предложение в избранное

PATCH  http://localhost:4000/users/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNhbUBwb3N0LmdvIiwibmFtZSI6IlNhbSIsImlkIjoiNjU0OGU1ODk1NmFlMDE1MDQ3NWJmOGE4IiwiaXNQcm8iOmZhbHNlLCJpYXQiOjE2OTk5ODQzNzAsImV4cCI6MTcwMDE1NzE3MH0.0gDlFXUk_4Nkdl15NmQD3q-HRsrcDszumE5ROkHmzow

{
  "offerId": "6532864f0fe8c4629c06f8fa",
  "toFavorite": true
}

###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNhbUBwb3N0LmdvIiwibmFtZSI6IlNhbSIsImlkIjoiNjU0OGU1ODk1NmFlMDE1MDQ3NWJmOGE4IiwiaXNQcm8iOmZhbHNlLCJpYXQiOjE2OTk5ODQzNzAsImV4cCI6MTcwMDE1NzE3MH0.0gDlFXUk_4Nkdl15NmQD3q-HRsrcDszumE5ROkHmzow

###

## Отправить изображение

PATCH http://localhost:4000/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNhbUBwb3N0LmdvIiwibmFtZSI6IlNhbSIsImlkIjoiNjU0OGU1ODk1NmFlMDE1MDQ3NWJmOGE4IiwiaXNQcm8iOmZhbHNlLCJpYXQiOjE2OTk5ODQzNzAsImV4cCI6MTcwMDE1NzE3MH0.0gDlFXUk_4Nkdl15NmQD3q-HRsrcDszumE5ROkHmzow
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screenshot.png"
Content-Type: image/png

< /Users/Arina/Desktop/screenshot.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
