# Пользователи
## Получить список предложений
GET http://localhost:4000/offers?limit=3 HTTP/1.1
Content-Type: application/json

###

## Получить список премиальных предложений
GET http://localhost:4000/offers/premium/Paris HTTP/1.1
Content-Type: application/json

###

## Создать новое предложение

POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InNhbUBwb3N0LmdvIiwibmFtZSI6IlNhbSIsImlkIjoiNjU1NTIzMWU5MmI0NDY5ZWU4NjQwNWQ3Iiwic3RhdHVzIjoicmVndWxhciIsImlhdCI6MTcwMDA3ODM4MiwiZXhwIjoxNzAwMjUxMTgyfQ.rVnGHvkyAVJEobCF0Yh-l1ALWsSPIYjdizxVGl6o-1U

{
  "title": "Nice house",
  "city": "Paris",
  "previewImage": "https://url-to-image/image.jpeg",
  "isPremium": false,
  "type": "house",
  "price": 1000,
  "description": "Really nice house. Very comfy",
  "images": [
    "https://url-to-image/image.jpeg",
    "https://url-to-image/image.jpeg",
    "https://url-to-image/image.jpeg",
    "https://url-to-image/image.jpeg",
    "https://url-to-image/image.jpeg",
    "https://url-to-image/image.jpeg"
  ],
  "bedrooms": 3,
  "maxGuests": 4,
  "goods": [
    "Breakfast"
  ],
  "location": {
    "latitude": 52.12345678901234,
    "longitude": 4.12345678901234
  },
  "hostId": "6532864f0fe8c4629c06f8e3"
}

###

## Получить полное предложение по идентификатору

GET http://localhost:4000/offers/6532864f0fe8c4629c06f8ed HTTP/1.1

###

## Удалить объявление по идентификатору

DELETE http://localhost:4000/offers/6532864f0fe8c4629c06f8e8 HTTP/1.1

###

## Обновить объявление по идентификатору

PATCH http://localhost:4000/offers/6532864f0fe8c4629c06f904 HTTP/1.1
Content-Type: application/json

{
  "title": "Very nice house",
  "description": "Very nice house (Offer check up)",
  "price": 100000
}

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/6532864f0fe8c4629c06f8ed/comments HTTP/1.1

###
